### PR TITLE
API: Clusters and TopicIdentity end points.

### PR DESCRIPTION
**Pull request by hanpeter**
#### What's this PR do?

This PR adds following API end points:
* `/api/status/clusters` => Returns a list of active and pending clusters and their metadata
* `/api/status/:c/topicIdentities` => Returns a list of topic identities for a given cluster

#### Where should the reviewer start?

* `app/controllers/api/KafkaStateCheck.scala/clusters()`
* `app/controllers/api/KafkaStateCheck.scala/topicIdentities()`

#### How should this be manually tested?

1. Go to `your-kafka-manager.com/api/status/clusters` in your favourite browser.
2. Verify the list of clusters are displayed in valid JSON.

#### Any background context you want to provide?

This work was implemented so that we can monitor various different metrics in our kafka clusters. The credit goes to @kelseylam and @khhirani.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by patelh** [comment]
That's a lot of commits for so few changes.

**Comment by patelh** [comment]
Closing this as the commits were merged as a part of #290

**Pull request closed without merging**
