### PR TITLE
allow functionality with Kafka 2.12-2.1.0

### PR DESCRIPTION
**Pull request by brandonpalmer**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by dynax60** [comment]
Thank you for this important pull request.

**Comment by Ashish123gs** [comment]
This is great.

Can we also add support for version 1.1.1 officially ?
It works fine.

**Comment by patelh** [comment]
lgtm @panditsurabhi can you merge this?  unless @gyehuda wants to add me back as collaborator to this repo.

**Comment by BenLloydPearson** [comment]
@patelh, I sent you an invite to have write privileges on this repo.

**Comment by patelh** [comment]
@BenLloydPearson thanks!

**Pull request merged**
