### PR TITLE
added travis config

### PR DESCRIPTION
**Pull request by davglass**
Starting this PR to test the travis config, hopefully it will be easy to make this green.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by davglass** [comment]
I'm not sure what it's doing at this point:

```
[info] Loading project definition from /home/travis/build/yahoo/kafka-manager/project
```

But it just hangs there on my Mac too.

@patelh Thoughts?

**Comment by davglass** [comment]
Ok, so it's doing **a lot** of stuff at that time and just not echoing out to the screen.

One build passed, one failed. The ones that failed on this test are all failing from downloads.

**Comment by patelh** [comment]
Can we remove 2.9.3, 2.10.1, we are only using 2.11.5 and just need to test it once since we don't cross compile to multiple versions of scala.

**Pull request merged**
