### PR TITLE
Reassign partitions with replication factor option

### PR DESCRIPTION
**Pull request by cipriansofronia**
The current feature for reassigning partitions doesn't allow you to update the replication factor, in case you've wrongly created a topic with an undesired replication. This offers you a way to change that in the `Generate Partition Assignments` step, by specifying the desired replication factor within the optional field.

### CODE REVIEW

**Comment by patelh** [comment]
You want to add a tool tip or note that this isn't required field?

**Comment by cipriansofronia** [comment]
It's an optional input field on the frontend side

**Comment by cipriansofronia** [comment]
@patelh, It's an optional input field on the frontend side with the desired replication factor.

**Comment by cipriansofronia** [comment]
@patelh, any follow up on this?

**Comment by brefre** [comment]
Thank you for creating this feature. I manually patched my installation.

**Comment by patelh** [comment]
can u fix conflicts? github isn't giving me option to resolve conflicts myself

**Comment by cipriansofronia** [comment]
@patelh, I fixed the conflicts :smiley_cat:

**Comment by patelh** [comment]
Somehow I missed your comment about fixing conflicts.  Sorry.  One more conflict to resolve.  If you want me to fix it, add me as contributor to your forked kafka-manager repo and I can update your branch.

**Comment by cipriansofronia** [comment]
@patelh, fixed the conflicts

**Pull request merged**
