### PR TITLE
Support kafka 0.10.x.x

### PR DESCRIPTION
**Pull request by fuji-151a**
I've added feature that was be able to select version 0.10.1.1, 0.10.2.0 and 0.10.2.1 from UI.
Tests are passing and the instance I'm running locally seems to be working properly.
And He is saying too. (See: #394)

Please check this pull request.
Thank you.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bigdata4u** [comment]
@fuji-151a Nice work. Mind agreeing to the terms pointed out above so this PR can be merged?

**Comment by fuji-151a** [comment]
@bigdata4u Thank, you!!
I have already agree CLA.

**Comment by bigdata4u** [comment]
@yahoocla could you please merge this PR

**Comment by patelh** [comment]
@fuji-151a please add tests for in ClusterConfig serialization/deserialization

**Comment by patelh** [comment]
@fuji-151a have you tested it with version 0.10.2.1?

**Comment by fuji-151a** [comment]
Thanks for the review @patelh !!
I have added test code. Please check this.

> have you tested it with version 0.10.2.1?

Yes, I have tested it with kafka version 0.10.2.1.
He is using it without any issues too. (See: #394)

**Comment by patelh** [comment]
lgtm

**Comment by bigdata4u** [comment]
Thanks guys

**Pull request merged**
