### PR TITLE
Issue #319: Added 0.10.0.1 and 0.10.1.0 support

### PR DESCRIPTION
**Pull request by lawrencemq**
I've added the basics of 0.10.0.1 and 0.10.1.0 support.  Tests are passing and the instance I'm running locally seems to be working properly.

Let me know if I missed anything.  Thanks!

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by lawrencemq** [comment]
I have since signed the CLA

**Comment by simplesteph** [comment]
how is this different than https://github.com/yahoo/kafka-manager/pull/282 ?

**Comment by lawrencemq** [comment]
Apologies - I didn't see that PR before I had started.  I just saw that Kafka Manager hadn't had 0.10+ in it and went for it! Sorry for jumping the gun.

**Comment by dbeckham** [comment]
I think the difference is that the changes in #282 were poorly tested, inexplicably remove 0.9.x related code, and broke backwards compatibility for some people.

The author of #282 made changes assuming that no one would use anything but 0.10.x.

**Comment by lawrencemq** [comment]
Closing this in favor of #282

**Pull request closed without merging**
