### PR TITLE
* add debian & rpm packaging capabilities

### PR DESCRIPTION
**Pull request by jib**
Most operations groups will want to deploy via their systems package manager, rather than from zipfile & extract. This adds native packaging capabilities by using sbt-native-packager: 

  http://www.scala-sbt.org/sbt-native-packager/gettingstarted.html

You now package the build by running:

```
# Debian
$ sbt debian:packageBin

# RPM
$ sbt rpm:packageBin
```

Note, there's no email address on record for the primary maintainer, or Yahoo OSS, so I had to choose 'yahoo@example.com' for the maintainer address. Please update that as appropriate.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jib** [comment]
This build failed with:

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

That looks like a misconfigured build in travis, since this isn't a Ruby project....

**Comment by patelh** [comment]
Travic CI config has been updated.  Going through PRs in order.

**Comment by patricklucas** [comment]
+1 for this. I'm already using this patch to deploy kafka-manager with a deb.

**Pull request merged**
