### PR TITLE
Send a message to a topic

### PR DESCRIPTION
**Pull request by Mogztter**
Adds a simple form to send a message to a topic.

**Send message operation**
send-message-action-topic

**Send message form**
send-message-form

Ref #130

### CODE REVIEW

**Comment by patelh** [comment]
I'd love to pull this in but I am not sure if everyone would be happy with allowing writes to topics.

**Comment by Mogztter** [comment]
We can maybe add a flag/switch to enable this feature ?

Having said that we already have a "Delete topic" button :)

**Comment by xushan** [comment]
i hope for added this feature,so we can test kafka cluster wether it's works right

**Comment by Mogztter** [comment]
@patelh I understand your concern, if you want if can add a flag to enable/disable this feature ?

**Comment by krishna81m** [comment]
Has this been merged? I don't see the post message option

**Comment by Mogztter** [comment]
No not yet. I'm not sure what needs to be done ?

**Comment by mageddo** [comment]
I think a Key and Partition would be  helpful

**Pull request closed without merging**
