### PR TITLE
Add in 1.0.0 and 0.11.0.2 as valid versions

### PR DESCRIPTION
**Pull request by icco**
The newest versions, both which came out in November, 2017: https://kafka.apache.org/downloads

I don't know if there are other compatibility changes that need to be made, but https://github.com/yahoo/kafka-manager/issues/451 implies that probably not.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by icco** [comment]
I signed the CLA

**Comment by icco** [comment]
This test fail looks unrelated and seems to be a bug in 0.10.0.1?

**Comment by icco** [comment]
@patelh I made this and tried to keep as close to https://github.com/yahoo/kafka-manager/pull/424 as possible. I didn't add 1.0.0 to Readme in case people find regressions?

**Comment by patelh** [comment]
Sorry been out on vacation, will look at this next week but first glace looks good to go.

**Comment by niklausxiao** [comment]
Kafka 1.0.0 have been released for 2 more months， any progress on this？

**Comment by nullne** [comment]
it seems everything is ok? when will it be merged into master branch?

**Comment by yzang** [comment]
When will this be merged into the master?

**Comment by TheMonolithX64** [comment]
Ran this locally and all seems fine. All tests passing as well. This resolves issue of "Sum of partition offsets" always 0 in #459 due to https://github.com/yahoo/kafka-manager/blob/master/app/kafka/manager/actor/cluster/KafkaStateActor.scala#L160

```...
[info] TestClusterConfig:  
[info] - invalid name  
[info] - invalid kafka version  
[info] - serialize and deserialize 0.8.1.1  
[info] - serialize and deserialize 0.8.2.0 +jmx credentials  
[info] - serialize and deserialize 0.8.2.0  
[info] - serialize and deserialize 0.8.2.1  
[info] - serialize and deserialize 0.8.2.2  
[info] - deserialize without version, jmxEnabled, and security protocol  
[info] - deserialize from 0.8.2-beta as 0.8.2.0  
[info] - deserialize from 0.9.0.1  
[info] - serialize and deserialize 0.10.0.0  
[info] - serialize and deserialize 0.10.1.0  
[info] - serialize and deserialize 0.10.1.1  
[info] - serialize and deserialize 0.10.2.0  
[info] - serialize and deserialize 0.10.2.1  
[info] - serialize and deserialize 0.11.0.0  
[info] - serialize and deserialize 0.11.0.2  
[info] - serialize and deserialize 1.0.0  
[info] ScalaTest  
[info] Run completed in 2 minutes, 51 seconds.  
[info] Total number of tests run: 155  
[info] Suites: completed 16, aborted 0  
[info] Tests: succeeded 155, failed 0, canceled 0, ignored 0, pending 0  
[info] All tests passed.  
[info] Passed: Total 155, Failed 0, Errors 0, Passed 155  
[success] Total time: 178 s, completed 09-Feb-2018 20:37:53```

**Pull request merged**
