### PR TITLE
Fix checkbox alignment

### PR DESCRIPTION
**Pull request by Firemango**
Checkbox was out of alignment, using the label field caused it to look wrong.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by Firemango** [comment]
I signed it

**Comment by patelh** [comment]
open and close request so CLA check is done again

**Comment by Firemango** [comment]
Thanks patelh. :)

**Pull request merged**
