### PR TITLE
add API for retrieving topic list from kafka manager

### PR DESCRIPTION
**Pull request by jisookim0513**

### CODE REVIEW

**Comment by jisookim0513** [comment]
@patelh the build fails with updating logkafka config test, but the test passes on my local machine. What could be the difference in the testing environment?

**Comment by patelh** [comment]
Yea, non-deterministic test, so it could fail depending on timing.

-Hiral

**Comment by patelh** [comment]
can you rebase this?

**Comment by jisookim0513** [comment]
@patelh rebased it

**Pull request merged**
