### PR TITLE
Add basic auth

### PR DESCRIPTION
**Pull request by mrwanny**
added a very basic http authentication filter so that malicious user does not have un-authentication access to perform destructive operation like deleting a topic.

thanks to https://github.com/Kaliber/play-basic-authentication-filter for the filter

### CODE REVIEW

**Comment by mrwanny** [comment]
@patelh rebased PR #202 to master

**Comment by patelh** [comment]
Sweet, will try it out tomorrow and merge it.

**Comment by sslavic** [comment]
This would close https://github.com/yahoo/kafka-manager/issues/141
Thanks @mrwanny for providing PR.

**Comment by miguelpuyol** [comment]
It works good! Well done @mrwanny

**Comment by patelh** [comment]
Merged.

**Pull request merged**
