### PR TITLE
Add Consumer offset and lag information

### PR DESCRIPTION
**Pull request by nzhang1220**

### CODE REVIEW

**Comment by nzhang1220** [comment]
Walmart Global eCommerce (@WalmartLabs) has been running multiple geographical Kafka clusters which are constantly monitored and managed by a "homemade" Kafka dashboard. The consumer offset and lag monitoring of @WalmartLabs "homemade" dashboard provides a clean view of each consumer group so that the users could see how their consumers perform and how far they are behind producers. This patch mostly comes from @WalmartLabs Kafka dashboard and has been made work for kafka-manager.

screen shot 2015-08-03 at 5 39 56 pm
screen shot 2015-08-04 at 6 05 02 pm
screen shot 2015-08-04 at 6 05 12 pm

**Comment by MichaelScofield** [comment]
any plans to merge this into master branch? looking forward to consumer lag check feature!

**Comment by aseev-xx** [comment]
Oh, it's really great feature. @nzhang1220 please tell us about any plans to merge this into master branch?

**Comment by patelh** [comment]
We've merged @cvcal PR which had similar functionality.  We've added an abstraction for offsets, namely OffsetCache.  There are two implementations, active and passive.  Active is using the code cvcal submiited, and the passive uses the same idea as submitted by @nzhang1220 to query ZK when a UI request comes in.  The passive mode is default as the active mode may not scale with large # of consumers.  Thank you for submitting this feature @nzhang1220

**Comment by nzhang1220** [comment]
@patelh sounds great

**Pull request closed without merging**
