### PR TITLE
Display Topic and Broker Sizes

### PR DESCRIPTION
**Pull request by jisookim0513**
Added an option to display topic and broker sizes. 
This works only after patch https://issues.apache.org/jira/browse/KAFKA-1614 is applied to Kafka.
Longer broker-view-update-seconds is recommended since BVActor queries sizes for all existing segments. I am currently using a version that doesn't fetch consumer data, but with consumer data getting fetched, Kafka Manager might be overloaded. So I plan to make fetching consumer data configurable.

screen shot 2015-10-28 at 12 50 01 am
screen shot 2015-10-28 at 12 50 17 am
screen shot 2015-10-28 at 12 50 28 am

### CODE REVIEW

**Comment by patelh** [comment]
Can you rebase or merge master?

**Comment by jisookim0513** [comment]
@patelh rebased it

**Comment by patelh** [comment]
Should I merge or did you want to add the option to enable/disable consumer offset ?

**Comment by jisookim0513** [comment]
Could you merge it? I'd like to have enable/disable consumer offset as a
separate PR.

**Pull request merged**
