### PR TITLE
Format offset values for readability

### PR DESCRIPTION
**Pull request by stephen-lazarionok**
The suggested implementation for https://github.com/yahoo/kafka-manager/issues/446

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by stephen-lazarionok** [comment]
CLA is done.

**Comment by stephen-lazarionok** [comment]
The CLA is signed.

**Comment by stephen-lazarionok** [comment]
Can someone review this one? For our team it's a really useful feature.

**Pull request merged**
